In [1]:
import numpy as np

In [2]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [3]:
def sigmoid_derivative(x):
    return x * (1 - x)

In [4]:
def binary_cross_entropy(y_true, y_pred):
    return -np.mean(y_true * np.log(y_pred + 1e-7) + (1 - y_true) * np.log(1 - y_pred + 1e-7))

In [5]:
def train_neural_network(X, y, epochs=10000, lr=0.1):
    input_dim = X.shape[1]
    weights = np.random.uniform(size=(input_dim, 1))
    bias = np.random.uniform(size=(1,))

    for epoch in range(epochs):
        linear_output = np.dot(X, weights) + bias
        predictions = sigmoid(linear_output)

        loss = binary_cross_entropy(y, predictions)

        error = predictions - y
        d_pred = error * sigmoid_derivative(predictions)

        weights -= lr * np.dot(X.T, d_pred)
        bias -= lr * np.sum(d_pred)

        if epoch % 1000 == 0:
            print(f"Epoch {epoch}, Loss: {loss:.4f}")
    
    return weights, bias

In [6]:
def predict(X, weights, bias):
    return sigmoid(np.dot(X, weights) + bias) >= 0.5

In [7]:
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

logic_gates = {
    "AND": np.array([[0], [0], [0], [1]]),
    "OR": np.array([[0], [1], [1], [1]]),
    "NAND": np.array([[1], [1], [1], [0]]),
    "NOR": np.array([[1], [0], [0], [0]]),
    "XOR": np.array([[0], [1], [1], [0]])
}

for gate_name, y in logic_gates.items():
    print(f"\nTraining for {gate_name} gate:")
    weights, bias = train_neural_network(X, y, epochs=10000, lr=0.1)
    predictions = predict(X, weights, bias).astype(int)
    print(f"Predictions for {gate_name} gate:\n{predictions.reshape(-1)}")


Training for AND gate:
Epoch 0, Loss: 0.9714
Epoch 1000, Loss: 0.1757
Epoch 2000, Loss: 0.1176
Epoch 3000, Loss: 0.0924
Epoch 4000, Loss: 0.0779
Epoch 5000, Loss: 0.0683
Epoch 6000, Loss: 0.0614
Epoch 7000, Loss: 0.0562
Epoch 8000, Loss: 0.0520
Epoch 9000, Loss: 0.0486
Predictions for AND gate:
[0 0 0 1]

Training for OR gate:
Epoch 0, Loss: 0.4033
Epoch 1000, Loss: 0.1193
Epoch 2000, Loss: 0.0794
Epoch 3000, Loss: 0.0626
Epoch 4000, Loss: 0.0530
Epoch 5000, Loss: 0.0466
Epoch 6000, Loss: 0.0420
Epoch 7000, Loss: 0.0385
Epoch 8000, Loss: 0.0357
Epoch 9000, Loss: 0.0334
Predictions for OR gate:
[0 1 1 1]

Training for NAND gate:
Epoch 0, Loss: 0.5919
Epoch 1000, Loss: 0.1761
Epoch 2000, Loss: 0.1178
Epoch 3000, Loss: 0.0925
Epoch 4000, Loss: 0.0779
Epoch 5000, Loss: 0.0683
Epoch 6000, Loss: 0.0614
Epoch 7000, Loss: 0.0562
Epoch 8000, Loss: 0.0520
Epoch 9000, Loss: 0.0486
Predictions for NAND gate:
[1 1 1 0]

Training for NOR gate:
Epoch 0, Loss: 1.2252
Epoch 1000, Loss: 0.1280
Epoch 20